query PageQuery {
  page(id: 501, idType: DATABASE_ID, asPreview: false) {
    content(format: RENDERED)
  }
}
query ListPages {
  pages {
    nodes {
      id
      databaseId
      title
    }
  }
}
query GetPageSEO ($id: ID!){
  page(id: $id, idType: DATABASE_ID) {
    seo {
      title
      metaDesc
      focuskw
      canonical
      opengraphType
    }
  }
}
query contentseo{
  __type(name: "ContentNode") {
    fields {
      name
      type {
        name
        kind
      }
    }
  }
}

query contentnode {
  __type(name: "ContentNode") {
    name
    kind
    fields {
      name
      type {
        name
        kind
      }
    }
  }
}